// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFineCore.EntityFramework;

namespace NFineCore.EntityFramework.Migrations
{
    [DbContext(typeof(NFineCoreDbContext))]
    partial class NFineCoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.Area", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Description");

                    b.Property<string>("EnCode");

                    b.Property<bool?>("EnabledMark");

                    b.Property<string>("FullName");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<int?>("Layers");

                    b.Property<long>("ParentId");

                    b.Property<string>("SimpleSpelling");

                    b.Property<int?>("SortCode");

                    b.HasKey("Id");

                    b.ToTable("sys_area");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.Attach", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("FileExt");

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<long>("FileSize");

                    b.Property<string>("FileType");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("ThumbPath");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("sys_attach");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.Dict", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Description");

                    b.Property<string>("EnCode");

                    b.Property<bool?>("EnabledMark");

                    b.Property<string>("FullName");

                    b.Property<bool?>("IsTree");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<int?>("Layers");

                    b.Property<long>("ParentId");

                    b.Property<int?>("SortCode");

                    b.HasKey("Id");

                    b.ToTable("sys_dict");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.DictItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Description");

                    b.Property<long>("DictId");

                    b.Property<bool?>("EnabledMark");

                    b.Property<bool?>("IsDefault");

                    b.Property<string>("ItemCode");

                    b.Property<string>("ItemName");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<int?>("Layers");

                    b.Property<long>("ParentId");

                    b.Property<string>("SimpleSpelling");

                    b.Property<int?>("SortCode");

                    b.HasKey("Id");

                    b.HasIndex("DictId");

                    b.ToTable("sys_dictitem");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.LoginLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Description");

                    b.Property<string>("IpAddress");

                    b.Property<string>("IpAddressLocation");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<bool?>("OperateResult");

                    b.Property<DateTime?>("OperateTime");

                    b.Property<string>("OperateType");

                    b.Property<long>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("sys_loginlog");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.OperateLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action");

                    b.Property<string>("Area");

                    b.Property<string>("Controller");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("Method");

                    b.Property<DateTime?>("OperateTime");

                    b.Property<string>("Parameter");

                    b.Property<long>("UserId");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("sys_operatelog");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.Organize", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<bool?>("AllowDelete");

                    b.Property<bool?>("AllowEdit");

                    b.Property<string>("AreaId");

                    b.Property<string>("CategoryId");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Email");

                    b.Property<string>("EnCode");

                    b.Property<bool?>("EnabledMark");

                    b.Property<string>("Fax");

                    b.Property<string>("FullName");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<int?>("Layers");

                    b.Property<string>("ManagerId");

                    b.Property<string>("MobilePhone");

                    b.Property<long>("ParentId");

                    b.Property<string>("ShortName");

                    b.Property<int?>("SortCode");

                    b.Property<string>("TelePhone");

                    b.Property<string>("Type");

                    b.Property<string>("WeChat");

                    b.HasKey("Id");

                    b.ToTable("sys_organize");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<long>("ObjectId");

                    b.Property<string>("ObjectType");

                    b.Property<long>("ResourceId");

                    b.Property<int?>("SortCode");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.ToTable("sys_permission");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.Position", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("AllowDelete");

                    b.Property<bool?>("AllowEdit");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Description");

                    b.Property<string>("EnCode");

                    b.Property<bool?>("EnabledMark");

                    b.Property<string>("FullName");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<long>("OrganizeId");

                    b.Property<int?>("SortCode");

                    b.HasKey("Id");

                    b.ToTable("sys_position");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.Resource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("AllowDelete");

                    b.Property<bool?>("AllowEdit");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Description");

                    b.Property<string>("EnCode");

                    b.Property<bool?>("EnabledMark");

                    b.Property<string>("FullName");

                    b.Property<string>("Icon");

                    b.Property<bool?>("IsDisplay");

                    b.Property<bool?>("IsExpand");

                    b.Property<bool?>("IsMenu");

                    b.Property<bool?>("IsPublic");

                    b.Property<string>("JsEvent");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<int?>("Layers");

                    b.Property<int?>("Location");

                    b.Property<string>("Module");

                    b.Property<string>("ObjectType");

                    b.Property<long>("ParentId");

                    b.Property<string>("PermissionCode");

                    b.Property<int?>("SortCode");

                    b.Property<bool?>("Split");

                    b.Property<string>("Target");

                    b.Property<string>("UrlAddress");

                    b.HasKey("Id");

                    b.ToTable("sys_resource");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool?>("AllowDelete");

                    b.Property<bool?>("AllowEdit");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Description");

                    b.Property<string>("EnCode");

                    b.Property<bool?>("EnabledMark");

                    b.Property<string>("FullName");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<long?>("OrganizeId");

                    b.Property<int?>("SortCode");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.HasIndex("OrganizeId");

                    b.ToTable("sys_role");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("Birthday");

                    b.Property<long>("CompanyId");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<long>("DepartmentId");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<bool?>("EnabledMark");

                    b.Property<byte?>("Gender");

                    b.Property<bool?>("IsAdministrator");

                    b.Property<DateTime?>("LastLoginTime");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("MobilePhone");

                    b.Property<string>("NickName");

                    b.Property<string>("Password");

                    b.Property<long>("PositionId");

                    b.Property<string>("RealName");

                    b.Property<string>("SecretKey");

                    b.Property<string>("TelePhone");

                    b.Property<byte?>("Type");

                    b.Property<string>("UserName");

                    b.Property<string>("WeChat");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PositionId");

                    b.ToTable("sys_user");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.UserRole", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("RoleId");

                    b.Property<bool?>("DeletedMark");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("sys_userrole");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.WeixinManage.WxImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppId");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("FileExt");

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<long?>("FileSize");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("MediaId");

                    b.Property<string>("MediaUrl");

                    b.Property<string>("ThumbPath");

                    b.HasKey("Id");

                    b.ToTable("wx_image");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.WeixinManage.WxMenu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppId");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("MenuData");

                    b.HasKey("Id");

                    b.ToTable("wx_menu");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.WeixinManage.WxNews", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppId");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("MediaId");

                    b.HasKey("Id");

                    b.ToTable("wx_news");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.WeixinManage.WxNewsItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Content");

                    b.Property<string>("ContentSourceUrl");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Digest");

                    b.Property<int>("Index");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<int>("NeedOpenComment");

                    b.Property<long?>("NewsId");

                    b.Property<int>("OnlyFansCanComment");

                    b.Property<int>("ShowCoverPic");

                    b.Property<long?>("ThumbId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("NewsId");

                    b.HasIndex("ThumbId");

                    b.ToTable("wx_newsitem");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.WeixinManage.WxOfficial", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Account");

                    b.Property<string>("AppId");

                    b.Property<string>("AppSecret");

                    b.Property<string>("AppType");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Description");

                    b.Property<bool?>("EnabledMark");

                    b.Property<string>("EncodingAESKey");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("Name");

                    b.Property<string>("Token");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("wx_official");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.WeixinManage.WxText", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppId");

                    b.Property<string>("Content");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("wx_text");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.WeixinManage.WxUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppId");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<int?>("GroupId");

                    b.Property<string>("HeadImgUrl");

                    b.Property<string>("Language");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("Nickname");

                    b.Property<string>("OpenId");

                    b.Property<string>("Province");

                    b.Property<string>("Remark");

                    b.Property<int?>("Sex");

                    b.Property<int?>("SubscribeStatus");

                    b.Property<DateTime?>("SubscribeTime");

                    b.Property<DateTime?>("SynchronisedTime");

                    b.Property<string>("TagId");

                    b.Property<string>("UnionId");

                    b.HasKey("Id");

                    b.ToTable("wx_user");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.WeixinManage.WxVideo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppId");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("FileExt");

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<long?>("FileSize");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("MediaId");

                    b.Property<string>("MediaUrl");

                    b.Property<string>("ThumbPath");

                    b.HasKey("Id");

                    b.ToTable("wx_video");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.WeixinManage.WxVoice", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AppId");

                    b.Property<DateTime?>("CreationTime");

                    b.Property<long?>("CreatorUserId");

                    b.Property<bool?>("DeletedMark");

                    b.Property<long?>("DeleterUserId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("FileExt");

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<long?>("FileSize");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<long?>("LastModifierUserId");

                    b.Property<string>("MediaId");

                    b.Property<string>("MediaUrl");

                    b.Property<string>("ThumbPath");

                    b.HasKey("Id");

                    b.ToTable("wx_voice");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.Attach", b =>
                {
                    b.HasOne("NFineCore.EntityFramework.Entity.SystemManage.User", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.DictItem", b =>
                {
                    b.HasOne("NFineCore.EntityFramework.Entity.SystemManage.Dict", "Dict")
                        .WithMany("DictItems")
                        .HasForeignKey("DictId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.Permission", b =>
                {
                    b.HasOne("NFineCore.EntityFramework.Entity.SystemManage.Resource", "Resource")
                        .WithMany()
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.Role", b =>
                {
                    b.HasOne("NFineCore.EntityFramework.Entity.SystemManage.Organize", "Organize")
                        .WithMany()
                        .HasForeignKey("OrganizeId");
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.User", b =>
                {
                    b.HasOne("NFineCore.EntityFramework.Entity.SystemManage.Organize", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NFineCore.EntityFramework.Entity.SystemManage.Organize", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NFineCore.EntityFramework.Entity.SystemManage.Position", "Position")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.SystemManage.UserRole", b =>
                {
                    b.HasOne("NFineCore.EntityFramework.Entity.SystemManage.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NFineCore.EntityFramework.Entity.SystemManage.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NFineCore.EntityFramework.Entity.WeixinManage.WxNewsItem", b =>
                {
                    b.HasOne("NFineCore.EntityFramework.Entity.WeixinManage.WxNews", "WxNews")
                        .WithMany("WxNewsItems")
                        .HasForeignKey("NewsId");

                    b.HasOne("NFineCore.EntityFramework.Entity.WeixinManage.WxImage", "Thumb")
                        .WithMany()
                        .HasForeignKey("ThumbId");
                });
#pragma warning restore 612, 618
        }
    }
}
